version: '3.0'

expectations:

  population_size: 500000


actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  generate_study_population_electively_unvaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_electively_unvaccinated --output-format feather
    needs: [vax_eligibility_inputs] 
    outputs:
      highly_sensitive:
        cohort: output/input_electively_unvaccinated.feather

  generate_study_population_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.feather

  generate_study_population_index:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_index --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_index.feather

  preprocess_data:
    run: r:latest analysis/preprocess_data.R
    needs: [generate_study_population_index, generate_study_population_vaccinated, generate_study_population_electively_unvaccinated]
    outputs:
      moderately_sensitive:
        describe_vaccinated: output/describe_input_vaccinated_stage0.txt
        describe_electively_unvaccinated: output/describe_input_electively_unvaccinated_stage0.txt
      highly_sensitive:
        cohort_vaccinated: output/input_vaccinated.rds
        cohort_electively_unvaccinated: output/input_electively_unvaccinated.rds
        describe_vaccinated: output/describe_input_vaccinated_stage0.txt
        describe_electively_unvaccinated: output/describe_input_electively_unvaccinated_stage0.txt
        venn_vaccinated: output/venn_vaccinated.rds
        venn_electively_unvaccinated: output/venn_electively_unvaccinated.rds

  stage1_data_cleaning_electively_unvaccinated:
    run: r:latest analysis/Stage1_data_cleaning.R output/input_electively_unvaccinated.rds electively_unvaccinated
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        refactoring: output/meta_data_factors_electively_unvaccinated.csv
        QA_rules: output/QA_summary_electively_unvaccinated.csv
        IE_criteria: output/Cohort_flow_electively_unvaccinated.csv
      highly_sensitive:
        cohort: output/input_electively_unvaccinated_stage1.rds

  stage1_data_cleaning_vaccinated:
    run: r:latest analysis/Stage1_data_cleaning.R output/input_vaccinated.rds vaccinated
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        refactoring: output/meta_data_factors_vaccinated.csv
        QA_rules: output/QA_summary_vaccinated.csv
        IE_criteria: output/Cohort_flow_vaccinated.csv
      highly_sensitive:
        cohort: output/input_vaccinated_stage1.rds