version: '3.0'

expectations:
  population_size: 100000

actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  generate_study_population_index:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_index --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_index.feather

  generate_study_population_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.feather

  generate_study_population_electively_unvaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_electively_unvaccinated --output-format feather
    needs: [vax_eligibility_inputs] 
    outputs:
      highly_sensitive:
        cohort: output/input_electively_unvaccinated.feather

  # preprocess_data:
  #   run: r:latest analysis/preprocess_data.R
  #   needs: [generate_study_population_index, generate_study_population_vaccinated, generate_study_population_electively_unvaccinated]
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input.rds
