version: '3.0'

expectations:
  population_size: 500000

actions:
  vax_eligibility_inputs:
    run: r:latest analysis/vax_eligibility_inputs.R
    outputs:
      highly_sensitive:
        vax_study_dates_json: output/vax_study_dates.json
        vax_jcvi_groups: output/vax_jcvi_groups.csv
        vax_eligible_dates: output/vax_eligible_dates.csv

  generate_study_population_electively_unvaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_electively_unvaccinated --output-format feather
    needs: [vax_eligibility_inputs] 
    outputs:
      highly_sensitive:
        cohort: output/input_electively_unvaccinated.feather

  generate_study_population_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.feather

  generate_study_population_index:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_index --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_index.feather

  preprocess_data:
    run: r:latest analysis/preprocess_data.R
    needs: [generate_study_population_index, generate_study_population_vaccinated, generate_study_population_electively_unvaccinated]
    outputs:
      highly_sensitive:
        cohort_vaccinated: output/input_vaccinated.rds
        cohort_electively_unvaccinated: output/input_electively_unvaccinated.rds
        venn_vaccinated: output/venn_vaccinated.rds
        venn_electively_unvaccinated: output/venn_electively_unvaccinated.rds

  covariate_critical_numbers_within_subpopulations_vaccinated_delta:
    run: r:latest analysis/Covariate_count_checks.R vaccinated_delta
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        covar_counts: output/covariates_counts_check_vaccinated_delta.csv

  covariate_critical_numbers_within_subpopulations_unvaccinated_delta:
    run: r:latest analysis/Covariate_count_checks.R unvaccinated_delta
    needs: [preprocess_data]
    outputs:
      moderately_sensitive:
        covar_counts: output/covariates_counts_check_unvaccinated_delta.csv