---
title: "input1_aer"
output: html_document
---
input1_aer. person days follow-up

Event count with less than or equal to 5 events have been marked as [Redacted] and the corresponding person years and incidence rates have also been marked as [Redacted].

Any results with redacted results will be at the top of the results file for easy review.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
library(readr)
knitr::opts_knit$set(root.dir = gsub("/analysis","",getwd()))
```

## Compiled input1_aer: subset of table2

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#analyses = "main"
#population = "vaccinated"
df2=read_csv(paste0("output/input1_aer_", analyses, "_", population, ".csv"))
df2 %>%
    datatable(extensions = 'Buttons',
              options = list(dom = 'Blfrtip',
                             buttons = c('copy', 'csv', 'excel', 'pdf', 'print' ),
                             lengthMenu = list(c(50,-1),
                                               c(50,"All"))))
```